//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.04.16 at 12:58:28 AM MSK 
//


package ru.mirea.pizzaclient.model.xml;

import lombok.Data;
import lombok.EqualsAndHashCode;

import javax.xml.bind.annotation.*;
import java.beans.Transient;


/**
 * <p>Java class for pizza complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="pizza"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="size" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="dough" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="toppings" type="{http://www.mirea.ru/pizza}toppings"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "pizza", propOrder = {
    "name",
    "size",
    "dough",
    "toppings"
})
@Data
@EqualsAndHashCode
public class Pizza {
    @XmlElement(required = true)
    protected String name;
    protected int size;
    @XmlElement(required = true)
    protected String dough;
    @XmlElement(required = true)
    protected Toppings toppings = new Toppings();

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the size property.
     * 
     */
    public int getSize() {
        return size;
    }

    /**
     * Sets the value of the size property.
     * 
     */
    public void setSize(int value) {
        this.size = value;
    }

    /**
     * Gets the value of the dough property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDough() {
        return dough;
    }

    /**
     * Sets the value of the dough property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDough(String value) {
        this.dough = value;
    }

    /**
     * Gets the value of the toppings property.
     * 
     * @return
     *     possible object is
     *     {@link Toppings }
     *     
     */
    public Toppings getToppings() {
        return toppings;
    }

    /**
     * Sets the value of the toppings property.
     * 
     * @param value
     *     allowed object is
     *     {@link Toppings }
     *     
     */
    public void setToppings(Toppings value) {
        this.toppings = value;
    }

}
